const departments = [
  // Main Campus
  "Biology",
  "Biotechnology",
  "Botany",
  "Business, Accounting and Finance",
  "Chemistry",
  "Commerce",
  "Computer Science",
  "Digital Communication and Media",
  "Economics",
  "Electrical Engineering",
  "Electronics",
  "English Literature",
  "Entrepreneurship",
  "Environmental Science",
  "Financial Technology",
  "Gender and Climate Change",
  "Information Security Engineering Technology",
  "International Relations",
  "Linguistics",
  "Law",
  "Management",
  "Media and Communication Studies",
  "Medical Laboratory Technology",
  "Microbiology",
  "Persian",
  "Philosophy",
  "Physics",
  "Political Science",
  "Psychology",
  "Public Policy",
  "Punjabi",
  "Sociology",
  "Translation Studies",
  "Turkish Language and Literature",
  "Urdu",
  "Zoology",

  // KSK Campus
  "Agriculture",
  "Archive Studies",
  "Art History",
  "B.Ed (1.5 Years)",
  "BFA Graphic Design",
  "BFA Painting",
  "Disaster Management",
  "Education",
  "Geography",
  "Global Studies",
  "History",
  "Islamic Studies",
  "Mathematics",
  "Physical Education and Sports Sciences",
  "Remote Sensing and Geographical Information System",
  "Statistics"
];
